#!/usr/bin/env bash
# Post-bootstrap activator for the identity + security MCP stack.
#
# Assumes ``deploy/setup_vps.sh`` has already run on this VPS (created
# the ``delftclaw`` system user, ``/opt/delftclaw`` venv, installed the
# templated systemd units). This script only does the subproject-specific
# work:
#
#   1. Create the persistent identity JSON under
#      ``/var/lib/delftclaw/identity/agent_identity.json``.
#   2. Write the per-instance env file
#      ``/etc/delftclaw/instances/<instance>.env`` consumed by
#      ``delftclaw-identity-mcp@<instance>.service`` and
#      ``delftclaw-security-mcp@<instance>.service``.
#   3. Stage the gateway/audit env knobs the colleagues' code reads.
#   4. Write the OpenClaw MCP-config JSON pointing at the two MCPs.
#
# Override any of the variables below by exporting them before running:
#
#   INSTANCE=my-vps NETWORK=testnet bash deploy/vps/bootstrap_security_identity.sh

set -Eeuo pipefail

REPO_DIR="${DELFTCLAW_REPO_DIR:-/opt/delftclaw}"

# Sourcing configs/host.env (if present) lets the operator override
# QWEN_BASE_URL / QWEN_MODEL / BTC_NETWORK / TAILSCALE_* once for the host
# and have both scenario_boot.py and this script pick them up. Existing
# environment variables win — same precedence as scenario_boot.py.
HOST_ENV_FILE="${HOST_ENV_FILE:-$REPO_DIR/configs/host.env}"
if [[ -f "$HOST_ENV_FILE" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOST_ENV_FILE"
  set +a
fi

INSTANCE="${INSTANCE:-${DELFTCLAW_AGENT_ID:-$(hostname -s)}}"
NETWORK="${NETWORK:-${DELFTCLAW_OPENCLAW_NETWORK:-regtest}}"

STATE_DIR="/var/lib/delftclaw/identity"
IDENTITY_PATH="${IDENTITY_PATH:-$STATE_DIR/agent_identity.json}"
ENV_FILE="/etc/delftclaw/instances/${INSTANCE}.env"
MCP_CONFIG="${MCP_CONFIG:-$REPO_DIR/configs/openclaw_security_identity_mcp_config.json}"

EXPERIMENT_ROOT="${DELFTCLAW_EXPERIMENT_ROOT:-/var/lib/delftclaw/experiments}"

IDENTITY_MCP_PORT="${IDENTITY_MCP_PORT:-7701}"
SECURITY_MCP_PORT="${SECURITY_MCP_PORT:-7702}"
GATEWAY_HOST="${DELFTCLAW_GATEWAY_HOST:-127.0.0.1}"
GATEWAY_PORT="${DELFTCLAW_GATEWAY_PORT:-8765}"

SERVICE_USER="delftclaw"

# Run a privileged command — passthrough when already root, sudo otherwise.
run_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

# Run a command as the delftclaw service user. We need ``sudo -u`` for the
# user switch even when the caller is already root.
run_as_service_user() {
  sudo -u "$SERVICE_USER" "$@"
}

cd "$REPO_DIR"

echo "[1/5] Creating identity state dir + JSON (${IDENTITY_PATH})"
run_root install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$STATE_DIR"
run_as_service_user env PYTHONPATH="$REPO_DIR" \
  "$REPO_DIR/venv/bin/python" - "$IDENTITY_PATH" "$NETWORK" <<'PY'
from pathlib import Path
import sys

from identity.agent_identity import AgentIdentity

path = Path(sys.argv[1])
network = sys.argv[2].upper()
path.parent.mkdir(parents=True, exist_ok=True)
if path.exists():
    identity = AgentIdentity.load(path)
else:
    identity = AgentIdentity(network=network, agent_index=0)
    identity.save(path)
print(identity.public_bundle()["agent_id"])
PY

echo "[2/5] Writing per-instance env file (${ENV_FILE})"
run_root install -d -o root -g "$SERVICE_USER" -m 0750 /etc/delftclaw/instances
ENV_BODY=$(cat <<EOF
# generated by deploy/vps/bootstrap_security_identity.sh — do not hand-edit
PYTHONPATH=${REPO_DIR}
HOME=${STATE_DIR}

NETWORK=${NETWORK}
IDENTITY_MCP_PORT=${IDENTITY_MCP_PORT}
IDENTITY_PATH=${IDENTITY_PATH}
SECURITY_MCP_PORT=${SECURITY_MCP_PORT}

# Colleagues' gateway + audit reads these directly; we keep them on the
# same env file so a single ``systemctl enable delftclaw-*@${INSTANCE}``
# starts every component with consistent state.
DELFTCLAW_AGENT_ID=${INSTANCE}
DELFTCLAW_GATEWAY_HOST=${GATEWAY_HOST}
DELFTCLAW_GATEWAY_PORT=${GATEWAY_PORT}
DELFTCLAW_GATEWAY_URL=http://${GATEWAY_HOST}:${GATEWAY_PORT}
DELFTCLAW_GATEWAY_MODE=${DELFTCLAW_GATEWAY_MODE:-defended}
DELFTCLAW_BAN_THRESHOLD=${DELFTCLAW_BAN_THRESHOLD:-30}
DELFTCLAW_MAX_TOOL_RISK=${DELFTCLAW_MAX_TOOL_RISK:-sensitive}
DELFTCLAW_LOG_PATH=/var/log/delftclaw/${INSTANCE}_append_only.jsonl

DELFTCLAW_USE_OPENCLAW_IDENTITY=true
DELFTCLAW_ENABLE_OPENCLAW_P2P=${DELFTCLAW_ENABLE_OPENCLAW_P2P:-false}
DELFTCLAW_OPENCLAW_NETWORK=${NETWORK^^}
DELFTCLAW_OPENCLAW_KEY_PATH=${IDENTITY_PATH}
DELFTCLAW_OPENCLAW_P2P_HOST=${DELFTCLAW_OPENCLAW_P2P_HOST:-0.0.0.0}
DELFTCLAW_OPENCLAW_P2P_PORT=${DELFTCLAW_OPENCLAW_P2P_PORT:-9000}
DELFTCLAW_OPENCLAW_WORKING_DIR=${REPO_DIR}

DELFTCLAW_BITCOIN_NETWORK=${DELFTCLAW_BITCOIN_NETWORK:-mock}
DELFTCLAW_BITCOIN_MIN_CONFIRMATIONS=${DELFTCLAW_BITCOIN_MIN_CONFIRMATIONS:-0}

DELFTCLAW_RUN_ID=${DELFTCLAW_RUN_ID:-${INSTANCE}-run001}
DELFTCLAW_EXPERIMENT_CONDITION=${DELFTCLAW_EXPERIMENT_CONDITION:-defended}
DELFTCLAW_EXPERIMENT_ROOT=${EXPERIMENT_ROOT}
DELFTCLAW_SUBQ3_CONDITION=${DELFTCLAW_SUBQ3_CONDITION:-gvisor}
DELFTCLAW_SUBQ3_MANIFEST=${EXPERIMENT_ROOT}/runs/subq3-${DELFTCLAW_SUBQ3_CONDITION:-gvisor}-run001/subq3_manifest.json
EOF
)
printf '%s\n' "$ENV_BODY" | run_root tee "$ENV_FILE" >/dev/null
run_root chmod 0640 "$ENV_FILE"
run_root chown "root:${SERVICE_USER}" "$ENV_FILE"

echo "[3/5] Preparing experiment workspace (${EXPERIMENT_ROOT})"
run_root install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$EXPERIMENT_ROOT"
run_root install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$EXPERIMENT_ROOT/responses"
run_root install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$EXPERIMENT_ROOT/secrets"

echo "[4/5] Writing OpenClaw MCP config (${MCP_CONFIG})"
mkdir -p "$(dirname "$MCP_CONFIG")"
"$REPO_DIR/venv/bin/python" - "$MCP_CONFIG" "$IDENTITY_MCP_PORT" "$SECURITY_MCP_PORT" <<'PY'
import json
from pathlib import Path
import sys

target = Path(sys.argv[1])
identity_port, security_port = sys.argv[2], sys.argv[3]
target.write_text(json.dumps({
    "mcp": {
        "servers": {
            "agent-identity": {
                "url": f"http://127.0.0.1:{identity_port}/mcp",
                "transport": "streamable-http",
                "description": "Cryptographic identity, wallet, signing, and verification tools."
            },
            "delftclaw-security": {
                "url": f"http://127.0.0.1:{security_port}/mcp",
                "transport": "streamable-http",
                "description": "DelftClaw defended gateway tools for seedboxes, reputation, files, audits, and metrics."
            }
        }
    }
}, indent=2) + "\n")
print(target)
PY

cat <<EOF

[5/5] Bootstrap complete.

Bring up the templated DelftClaw MCP units for instance '${INSTANCE}':

  sudo systemctl enable --now delftclaw-identity-mcp@${INSTANCE}.service
  sudo systemctl enable --now delftclaw-security-mcp@${INSTANCE}.service

Tail logs:

  journalctl -u delftclaw-identity-mcp@${INSTANCE}.service -f
  journalctl -u delftclaw-security-mcp@${INSTANCE}.service -f

(The colleagues' non-templated gateway + seedbox-audit units still install
via deploy/vps/install_security_identity_services.sh if you need them.)
EOF
