#!/usr/bin/env bash
# Installs + (re)starts the LLM proxy on this host.
#
# Inputs (env vars expected from the caller):
#   LLM_API_KEYS       — comma-separated list of API keys (required)
#   LLM_PROXY_PORT     — port for the proxy to bind on (default 11600)
#   LLM_PROXY_UPSTREAM — OpenAI-compat upstream URL
#                        (default https://api.anthropic.com/v1)
#
# Run via:
#   LLM_API_KEYS="sk-ant-..." bash deploy/install_llm_proxy.sh
#
# Idempotent: safe to re-run when keys / port / upstream change. On first
# run after the gemini→llm rename it also stops + disables the legacy
# delftclaw-gemini-proxy unit so the two don't fight over the port.
set -euo pipefail

PORT="${LLM_PROXY_PORT:-11600}"
UPSTREAM="${LLM_PROXY_UPSTREAM:-https://api.anthropic.com/v1}"
SERVICE_USER="${SERVICE_USER:-delftclaw}"
ETC_FILE=/etc/delftclaw/llm.env
LEGACY_ETC_FILE=/etc/delftclaw/gemini.env
UNIT_NAME=delftclaw-llm-proxy
LEGACY_UNIT_NAME=delftclaw-gemini-proxy
REPO_ROOT="${REPO_ROOT:-/opt/delftclaw}"

if [[ -z "${LLM_API_KEYS:-}" ]]; then
  echo "LLM_API_KEYS env var is empty — refusing to install" >&2
  exit 2
fi

# One-time cleanup of the legacy gemini-named unit.
if systemctl list-unit-files "${LEGACY_UNIT_NAME}.service" --no-legend 2>/dev/null \
     | grep -q "${LEGACY_UNIT_NAME}"; then
  echo "[install] removing legacy ${LEGACY_UNIT_NAME}.service"
  systemctl stop "${LEGACY_UNIT_NAME}" 2>/dev/null || true
  systemctl disable "${LEGACY_UNIT_NAME}" 2>/dev/null || true
  rm -f "/etc/systemd/system/${LEGACY_UNIT_NAME}.service"
  rm -f "${LEGACY_ETC_FILE}"
  systemctl daemon-reload
fi

echo "[install] writing ${ETC_FILE}"
install -d -m 0750 -o root -g "${SERVICE_USER}" /etc/delftclaw
umask 0027
cat > "${ETC_FILE}" <<EOF
# Auto-generated by deploy/install_llm_proxy.sh — do not hand-edit.
# Re-run the script to update keys / port / upstream.
LLM_API_KEYS=${LLM_API_KEYS}
LLM_PROXY_PORT=${PORT}
LLM_PROXY_UPSTREAM=${UPSTREAM}
EOF
chmod 0640 "${ETC_FILE}"
chown root:"${SERVICE_USER}" "${ETC_FILE}"

echo "[install] installing systemd unit"
cp "${REPO_ROOT}/deploy/systemd/${UNIT_NAME}.service" \
   "/etc/systemd/system/${UNIT_NAME}.service"
systemctl daemon-reload
systemctl enable "${UNIT_NAME}" >/dev/null

# Always restart so a re-run picks up new keys / port / upstream.
echo "[install] (re)starting ${UNIT_NAME}"
systemctl restart "${UNIT_NAME}"
sleep 2

if systemctl is-active --quiet "${UNIT_NAME}"; then
  echo "[install] ${UNIT_NAME}: active"
else
  echo "[install] ${UNIT_NAME}: FAILED — recent journal:" >&2
  journalctl -u "${UNIT_NAME}" --no-pager -n 30 >&2
  exit 1
fi

# Smoke-test the listener.
if HEALTH=$(curl -sf -m 5 "http://127.0.0.1:${PORT}/healthz"); then
  echo "[install] healthz: ${HEALTH}"
else
  echo "[install] healthz: NO RESPONSE on port ${PORT}" >&2
  exit 1
fi
