#!/bin/bash
###############################################################################
# setup_bitcoin_regtest.sh
#
# Initialize a headless bitcoind node in -regtest mode with pre-funded demo
# wallets. Suitable for running on a Linux VPS alongside DelftClaw agents.
#
# Usage:
#   ./deploy/setup_bitcoin_regtest.sh [OPTIONS]
#
# Options:
#   --bitcoin-data /path/to/dir    Bitcoin data directory (default: ~/.bitcoin)
#   --rpc-port 18443               JSON-RPC listen port (default: 18443)
#   --rpc-bind 127.0.0.1           JSON-RPC bind address (default: 127.0.0.1)
#   --bitcoin-cli /path/to/cli     Path to bitcoin-cli binary (default: bitcoin-cli)
#   --bitcoind /path/to/daemon     Path to bitcoind binary (default: bitcoind)
#   --python-bin /path/to/python   Path to Python binary (default: python3)
#   --help                          Show this help
#
# Environment Variables:
#   BITCOIN_CONF          Override Bitcoin config file path
#   OPENCLAW_SEED         Seed for wallet derivation (hex, 64 chars)
#   BITCOIN_CHAIN_ID      Network ID (default: regtest)
#   BOB_TARGET_BALANCE_SATS  Minimum Bob balance (default: 20000)
#
# The script will:
#   1. Ensure bitcoind is running in regtest mode
#   2. Create demo wallets (alice, bob, charlie, dave)
#   3. Mine 101+ blocks so UTXOs are spendable
#   4. Fund each wallet with demo satoshis
#   5. Output wallet addresses and private keys for testing
#
###############################################################################

set -euo pipefail

# Defaults
BITCOIN_DATA="${HOME}/.bitcoin"
RPC_PORT=18443
RPC_BIND="127.0.0.1"
BITCOIN_CLI="${BITCOIN_CLI:-bitcoin-cli}"
BITCOIND="${BITCOIND:-bitcoind}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
REGTEST_CHAIN="regtest"
BOB_TARGET_BALANCE_SATS="${BOB_TARGET_BALANCE_SATS:-20000}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --bitcoin-data)
            BITCOIN_DATA="$2"
            shift 2
            ;;
        --rpc-port)
            RPC_PORT="$2"
            shift 2
            ;;
        --rpc-bind)
            RPC_BIND="$2"
            shift 2
            ;;
        --bitcoin-cli)
            BITCOIN_CLI="$2"
            shift 2
            ;;
        --bitcoind)
            BITCOIND="$2"
            shift 2
            ;;
        --python-bin)
            PYTHON_BIN="$2"
            shift 2
            ;;
        --help)
            head -20 "$0" | tail -n +3
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Create Bitcoin data directory
mkdir -p "$BITCOIN_DATA/$REGTEST_CHAIN"

# Write bitcoin.conf
BITCOIN_CONF="${BITCOIN_CONF:-$BITCOIN_DATA/bitcoin.conf}"
cat > "$BITCOIN_CONF" << EOF
# DelftClaw Bitcoin Regtest Configuration
# Generated by setup_bitcoin_regtest.sh

# Network
# Note: network-specific settings (like rpcbind/rpcport) must be placed inside
# a [regtest] section in bitcoin.conf. We start bitcoind with -regtest, so
# leave the global config for common options and put regtest-only options below.

# Connection (global)
server=1
rpcallowip=127.0.0.1
rpcallowip=0.0.0.0/0

# Regtest-specific overrides
[regtest]
rpcport=$RPC_PORT
rpcbind=$RPC_BIND
rpcuser=admin
rpcpassword=admin

# Mining + Block generation
disablewallet=0
keypool=0

# Performance (for demo/test only, NOT for production)
txindex=1

# Chain management
blockfilterindex=1

# Logging
debug=rpc
debug=walletdb

# Data directory
datadir=$BITCOIN_DATA

EOF

echo "[*] Bitcoin config written to $BITCOIN_CONF"

# Run a bitcoin-cli command without retrying.
# Use this for real RPC calls so errors are visible immediately.
btc() {
    "$BITCOIN_CLI" -datadir="$BITCOIN_DATA" -regtest "$@"
}

# Wait until the daemon responds successfully.
btc_wait() {
    local retries=0
    while ! btc "$@" >/dev/null 2>&1; do
        if [ $retries -ge 60 ]; then
            echo "[!] Bitcoin daemon did not respond after 60 seconds" >&2
            return 1
        fi
        sleep 1
        retries=$((retries + 1))
    done
}

btc_to_sats() {
    "$PYTHON_BIN" - "$1" <<'PY'
from decimal import Decimal
import sys

print(int((Decimal(sys.argv[1]) * Decimal(100000000)).to_integral_value()))
PY
}

sats_to_btc() {
    "$PYTHON_BIN" - "$1" <<'PY'
from decimal import Decimal
import sys

print(f"{Decimal(int(sys.argv[1])) / Decimal(100000000):.8f}")
PY
}

stable_wallet_label() {
    local wallet_name="$1"
    printf 'delftclaw:%s:primary\n' "$wallet_name"
}

wallet_labeled_address() {
    local wallet_name="$1"
    local label
    local existing
    label="$(stable_wallet_label "$wallet_name")"

    existing="$(
        btc -rpcwallet="$wallet_name" getaddressesbylabel "$label" 2>/dev/null \
            | "$PYTHON_BIN" -c 'import json, sys; data = json.load(sys.stdin); print(sorted(data)[0] if data else "")' \
            2>/dev/null || true
    )"
    if [ -n "$existing" ]; then
        printf '%s\n' "$existing"
        return 0
    fi

    btc -rpcwallet="$wallet_name" getnewaddress "$label" bech32
}

wallet_is_loaded() {
    local wallet_name="$1"
    btc listwallets 2>/dev/null | grep -q "\"$wallet_name\""
}

wallet_disk_path() {
    local wallet_name="$1"
    local new_path="$BITCOIN_DATA/$REGTEST_CHAIN/wallets/$wallet_name"
    local legacy_path="$BITCOIN_DATA/$REGTEST_CHAIN/$wallet_name"

    if [ -d "$new_path" ]; then
        printf '%s\n' "$new_path"
    elif [ -d "$legacy_path" ]; then
        printf '%s\n' "$legacy_path"
    fi
}

ensure_wallet() {
    local wallet_name="$1"
    local wallet_path

    if wallet_is_loaded "$wallet_name"; then
        echo "  ✓ Wallet '$wallet_name' already loaded"
        return 0
    fi

    wallet_path="$(wallet_disk_path "$wallet_name" || true)"
    if [ -n "$wallet_path" ]; then
        if btc loadwallet "$wallet_path" >/dev/null 2>&1; then
            echo "  ✓ Loaded existing wallet '$wallet_name'"
            return 0
        fi

        echo "[!] Found existing wallet data for '$wallet_name' at '$wallet_path', but loading failed" >&2
        return 1
    fi

    btc createwallet "$wallet_name" >/dev/null
    echo "  ✓ Created wallet '$wallet_name'"
}

# Start bitcoind in regtest mode (background)
echo "[*] Starting bitcoind in -regtest mode..."
"$BITCOIND" -datadir="$BITCOIN_DATA" -regtest -daemon

# Wait for RPC to be available
echo "[*] Waiting for bitcoind RPC to be ready..."
for i in {1..60}; do
    if btc getblockcount >/dev/null 2>&1; then
        echo "[+] bitcoind is ready"
        break
    fi
    if [ $i -eq 60 ]; then
        echo "[!] bitcoind failed to start" >&2
        exit 1
    fi
    sleep 1
done

# Create named wallets for demo agents
echo "[*] Creating agent wallets..."
for agent in alice bob charlie dave; do
    ensure_wallet "$agent"
done

# Get current block count
CURRENT_BLOCKS=$(btc getblockcount)
echo "[*] Current block height: $CURRENT_BLOCKS"

# Mine initial blocks if not enough
BLOCKS_NEEDED=101
if [ "$CURRENT_BLOCKS" -lt "$BLOCKS_NEEDED" ]; then
    BLOCKS_TO_MINE=$((BLOCKS_NEEDED - CURRENT_BLOCKS))
    echo "[*] Mining $BLOCKS_TO_MINE blocks to reach maturity threshold..."
    btc generatetoaddress "$BLOCKS_TO_MINE" "$(wallet_labeled_address alice)" > /dev/null
    echo "  ✓ Mined blocks, now at height $(btc getblockcount)"
fi

# Bob's regtest_transfer admission donation is exactly 10,000 sats. Fund him
# above that amount so Bitcoin Core can also pay the transaction fee.
BOB_BALANCE_BTC=$(btc -rpcwallet=bob getbalance)
BOB_BALANCE_SATS=$(btc_to_sats "$BOB_BALANCE_BTC")
if [ "$BOB_BALANCE_SATS" -lt "$BOB_TARGET_BALANCE_SATS" ]; then
    FUND_SATS=$((BOB_TARGET_BALANCE_SATS - BOB_BALANCE_SATS))
    FUND_BTC=$(sats_to_btc "$FUND_SATS")
    BOB_ADDR=$(wallet_labeled_address bob)
    echo "[*] Funding bob with $FUND_SATS sats ($FUND_BTC BTC) for admission + fee headroom..."
    btc -rpcwallet=alice -named sendtoaddress \
        address="$BOB_ADDR" \
        amount="$FUND_BTC" \
        fee_rate=1 >/dev/null
    btc generatetoaddress 1 "$(wallet_labeled_address alice)" >/dev/null
    echo "  OK Bob balance is now $(btc -rpcwallet=bob getbalance) BTC"
else
    echo "[*] Bob already has $BOB_BALANCE_SATS sats; target is $BOB_TARGET_BALANCE_SATS sats"
fi

# Get addresses for each agent and display summary
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Bitcoin Regtest Initialization Complete             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Configuration:"
echo "  Bitcoin Data Dir: $BITCOIN_DATA"
echo "  Config File:     $BITCOIN_CONF"
echo "  RPC Port:        $RPC_PORT"
echo "  RPC Bind:        $RPC_BIND"
echo "  Block Height:    $(btc getblockcount)"
echo ""
echo "Wallets:"

# Function to get wallet balance and display
show_wallet_info() {
    local wallet_name="$1"
    echo ""
    echo "  $wallet_name:"

    # Get wallet info
    local wallet_info
    wallet_info=$(btc -rpcwallet="$wallet_name" getwalletinfo 2>/dev/null || echo "{}")

    # Get stable scenario address
    local addr
    addr=$(wallet_labeled_address "$wallet_name" 2>/dev/null || echo "ERROR")

    echo "    Address: $addr"

    # Try to get balance
    local balance
    balance=$(btc -rpcwallet="$wallet_name" getbalance 2>/dev/null || echo "0")
    echo "    Balance: $balance BTC"
}

for agent in alice bob charlie dave; do
    show_wallet_info "$agent"
done

echo ""
echo "To mine more blocks (fund wallets):"
echo "  bitcoin-cli -regtest generatetoaddress 50 <address>"
echo ""
echo "To get wallet balance:"
echo "  bitcoin-cli -regtest -rpcwallet=<wallet> getbalance"
echo ""
echo "To get a new address:"
echo "  bitcoin-cli -regtest -rpcwallet=<wallet> getnewaddress"
echo ""
echo "RPC connection string for agents:"
echo "  http://127.0.0.1:$RPC_PORT"
echo ""
