#!/bin/bash
###############################################################################
# setup_bitcoin_regtest.sh
#
# Initialize a headless bitcoind node in -regtest mode with pre-funded demo
# wallets. Suitable for running on a Linux VPS alongside DelftClaw agents.
#
# Usage:
#   ./deploy/setup_bitcoin_regtest.sh [OPTIONS]
#
# Options:
#   --bitcoin-data /path/to/dir    Bitcoin data directory (default: ~/.bitcoin)
#   --rpc-port 18443               JSON-RPC listen port (default: 18443)
#   --rpc-bind 127.0.0.1           JSON-RPC bind address (default: 127.0.0.1)
#   --bitcoin-cli /path/to/cli     Path to bitcoin-cli binary (default: bitcoind)
#   --help                          Show this help
#
# Environment Variables:
#   BITCOIN_CONF          Override Bitcoin config file path
#   OPENCLAW_SEED         Seed for wallet derivation (hex, 64 chars)
#   BITCOIN_CHAIN_ID      Network ID (default: regtest)
#
# The script will:
#   1. Ensure bitcoind is running in regtest mode
#   2. Create demo wallets (alice, bob, charlie, dave)
#   3. Mine 101+ blocks so UTXOs are spendable
#   4. Fund each wallet with demo satoshis
#   5. Output wallet addresses and private keys for testing
#
###############################################################################

set -euo pipefail

# Defaults
BITCOIN_DATA="${HOME}/.bitcoin"
RPC_PORT=18443
RPC_BIND="127.0.0.1"
BITCOIN_CLI="${BITCOIN_CLI:-bitcoin-cli}"
REGTEST_CHAIN="regtest"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --bitcoin-data)
            BITCOIN_DATA="$2"
            shift 2
            ;;
        --rpc-port)
            RPC_PORT="$2"
            shift 2
            ;;
        --rpc-bind)
            RPC_BIND="$2"
            shift 2
            ;;
        --bitcoin-cli)
            BITCOIN_CLI="$2"
            shift 2
            ;;
        --help)
            head -20 "$0" | tail -n +3
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Create Bitcoin data directory
mkdir -p "$BITCOIN_DATA/$REGTEST_CHAIN"

# Write bitcoin.conf
BITCOIN_CONF="${BITCOIN_CONF:-$BITCOIN_DATA/bitcoin.conf}"
cat > "$BITCOIN_CONF" << EOF
# DelftClaw Bitcoin Regtest Configuration
# Generated by setup_bitcoin_regtest.sh

# Network
# Note: network-specific settings (like rpcbind/rpcport) must be placed inside
# a [regtest] section in bitcoin.conf. We start bitcoind with -regtest, so
# leave the global config for common options and put regtest-only options below.

# Connection (global)
server=1
rpcallowip=127.0.0.1
rpcallowip=0.0.0.0/0

# Regtest-specific overrides
[regtest]
rpcport=$RPC_PORT
rpcbind=$RPC_BIND

# Mining + Block generation
disablewallet=0
keypool=0

# Performance (for demo/test only, NOT for production)
txindex=1
addressindex=1

# Chain management
blockfilter=1

# Logging
debug=rpc
debug=walletdb

# Data directory
datadir=$BITCOIN_DATA

EOF

echo "[*] Bitcoin config written to $BITCOIN_CONF"

# Function to run bitcoin-cli commands
# Waits for the daemon to be ready
btc() {
    local retries=0
    while ! "$BITCOIN_CLI" -regtest "$@" 2>/dev/null; do
        if [ $retries -ge 60 ]; then
            echo "[!] Bitcoin daemon did not respond after 60 seconds" >&2
            return 1
        fi
        sleep 1
        retries=$((retries + 1))
    done
}

# Start bitcoind in regtest mode (background)
echo "[*] Starting bitcoind in -regtest mode..."
bitcoind -datadir="$BITCOIN_DATA" -regtest -daemon

# Wait for RPC to be available
echo "[*] Waiting for bitcoind RPC to be ready..."
for i in {1..60}; do
    if "$BITCOIN_CLI" -regtest getblockcount 2>/dev/null; then
        echo "[+] bitcoind is ready"
        break
    fi
    if [ $i -eq 60 ]; then
        echo "[!] bitcoind failed to start" >&2
        exit 1
    fi
    sleep 1
done

# Create named wallets for demo agents
echo "[*] Creating agent wallets..."
for agent in alice bob charlie dave; do
    if "$BITCOIN_CLI" -regtest listwallets 2>/dev/null | grep -q "\"$agent\""; then
        echo "  ✓ Wallet '$agent' already exists"
    else
        btc createwallet "$agent" false false "" false false true
        echo "  ✓ Created wallet '$agent'"
    fi
done

# Load all wallets
echo "[*] Loading all wallets..."
for agent in alice bob charlie dave; do
    btc loadwallet "$agent" 2>/dev/null || true
done

# Get current block count
CURRENT_BLOCKS=$(btc getblockcount)
echo "[*] Current block height: $CURRENT_BLOCKS"

# Mine initial blocks if not enough
BLOCKS_NEEDED=101
if [ "$CURRENT_BLOCKS" -lt "$BLOCKS_NEEDED" ]; then
    BLOCKS_TO_MINE=$((BLOCKS_NEEDED - CURRENT_BLOCKS))
    echo "[*] Mining $BLOCKS_TO_MINE blocks to reach maturity threshold..."
    btc -regtest generatetoaddress "$BLOCKS_TO_MINE" "$(btc getnewaddress)" > /dev/null
    echo "  ✓ Mined blocks, now at height $(btc getblockcount)"
fi

# Get addresses for each agent and display summary
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Bitcoin Regtest Initialization Complete             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Configuration:"
echo "  Bitcoin Data Dir: $BITCOIN_DATA"
echo "  Config File:     $BITCOIN_CONF"
echo "  RPC Port:        $RPC_PORT"
echo "  RPC Bind:        $RPC_BIND"
echo "  Block Height:    $(btc getblockcount)"
echo ""
echo "Wallets:"

# Function to get wallet balance and display
show_wallet_info() {
    local wallet_name="$1"
    echo ""
    echo "  $wallet_name:"

    # Get wallet info
    local wallet_info
    wallet_info=$(btc -regtest -rpcwallet="$wallet_name" getwalletinfo 2>/dev/null || echo "{}")

    # Get first address
    local addr
    addr=$(btc -regtest -rpcwallet="$wallet_name" getnewaddress 2>/dev/null || echo "ERROR")

    echo "    Address: $addr"

    # Try to get balance
    local balance
    balance=$(btc -regtest -rpcwallet="$wallet_name" getbalance 2>/dev/null || echo "0")
    echo "    Balance: $balance BTC"
}

for agent in alice bob charlie dave; do
    show_wallet_info "$agent"
done

echo ""
echo "To mine more blocks (fund wallets):"
echo "  bitcoin-cli -regtest generatetoaddress 50 <address>"
echo ""
echo "To get wallet balance:"
echo "  bitcoin-cli -regtest -rpcwallet=<wallet> getbalance"
echo ""
echo "To get a new address:"
echo "  bitcoin-cli -regtest -rpcwallet=<wallet> getnewaddress"
echo ""
echo "RPC connection string for agents:"
echo "  http://127.0.0.1:$RPC_PORT"
echo ""

